FROM node:22-alpine

WORKDIR /usr/src/app

# Install openssl for Prisma Client execution inside alpine
RUN apk add --no-cache openssl

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install

COPY . .

# Generate Prisma Client specifically for the Linux container architecture
RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
