import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import {
  IsDate,
  IsNotEmpty,
  IsNumber,
  IsOptional,
  IsString,
  Min,
} from 'class-validator';

export class CashDetailsDto {
  @ApiProperty({
    example: 500.0,
    description: 'Total physical cash provided by the customer',
  })
  @IsNotEmpty()
  @IsNumber()
  @Min(0)
  @Type(() => Number)
  cash_tendered!: number;

  @ApiProperty({
    example: 50.0,
    description: 'Calculated change returned to the customer',
  })
  @IsNotEmpty()
  @IsNumber()
  @Min(0)
  @Type(() => Number)
  change_given!: number;
}

export class GCashDetailsDto {
  @ApiProperty({
    example: '123456789012',
    description: 'Unique transaction/reference code generated by GCash',
  })
  @IsNotEmpty()
  @IsString()
  reference_number!: string;

  @ApiPropertyOptional({
    example: '09171234567',
    description: 'Sender mobile number registered with GCash',
  })
  @IsOptional()
  @IsString()
  gcash_mobile_number?: string;
}

export class CreditDetailsDto {
  @ApiPropertyOptional({
    example: '2026-08-27T00:00:00.000Z',
    description: 'Due date or transaction agreement date for store credit',
  })
  @IsNotEmpty()
  @Type(() => Date)
  @IsDate()
  date?: Date;
}
